fn main() {
    // The e2e capability (pilot + wdio permissions) may only exist in
    // `--features e2e` builds: without the feature the plugin crates are out
    // of the dependency graph and tauri-build hard-fails on permissions it
    // cannot resolve (sweep finding X1). Generate/remove it around the build
    // so `capabilities/` is always consistent with the feature set. Builds
    // with different feature sets must not run in parallel in one worktree
    // (they race on this file).
    let e2e = std::path::Path::new("capabilities").join("e2e.json");
    if std::env::var("CARGO_FEATURE_E2E").is_ok() {
        let json = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "e2e",
  "description": "E2E/dogfooding permissions (sweep finding X1): the pilot + WebdriverIO plugins, compiled in and registered only in `--features e2e` debug builds. Generated by build.rs; do not edit.",
  "windows": ["main"],
  "permissions": ["pilot:default", "wdio:default"]
}"#;
        // Write only on content change: tauri-build watches `capabilities/`,
        // so an mtime churn would re-run this script on every build.
        if std::fs::read_to_string(&e2e).ok().as_deref() != Some(json) {
            std::fs::write(&e2e, json).expect("write capabilities/e2e.json");
        }
    } else if e2e.exists() {
        std::fs::remove_file(&e2e).expect("remove capabilities/e2e.json");
    }

    tauri_build::build()
}
